### ISSUE TITLE
Can't install with gem install spriteful

### ISSUE THREAD

**Issue by reinaldoferreira** [lucasmazza/spriteful#27]
$ sudo gem install spriteful
Building native extensions.  This could take a while...
ERROR:  Error installing spriteful:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20150311-15967-coizeg.rb extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for xcrun... yes
checking for Magick-config... yes
checking for ImageMagick version >= 6.4.9... yes
/usr/local/bin/Magick-config: line 41: pkg-config: command not found
/usr/local/bin/Magick-config: line 47: pkg-config: command not found
/usr/local/bin/Magick-config: line 50: pkg-config: command not found
/usr/local/bin/Magick-config: line 53: pkg-config: command not found
checking for stdint.h... yes
checking for sys/types.h... yes
checking for wand/MagickWand.h... no

Can't install RMagick 2.13.4. Can't find MagickWand.h.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by lucasmazza** [comment]
This seems to be an issue with your ImageMagick/pkg-config installation. Some StackOverflow threads ([like this one](http://stackoverflow.com/questions/23684133/cant-install-rmagick-pkg-config-command-not-found)) recommend reinstalling/installing pkg-config through brew and check if ImageMagick is working as expected.
